name: "Chef John J. O'Leary"
favicon: null
layout_spectrum: 0
typography_spectrum: 0.99785
title: 'Sour, Spicy, Funky'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fefefe'
    - '#317ec2'
    - '#001400'
    - '#004252'
    - '#387200'
  brandStrength: 0.076858
  lightness: 1
  saturation: 0.1875
  rhythmicContrast: 0.5
purpose:
  - name: null
    item: null
    url: null
