name: chefjohnjoleary
favicon: null
layout_spectrum: 0.74639
typography_spectrum: 0.06949
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#001534'
    - '#99ad91'
    - '#fee8b6'
    - '#006070'
    - '#518e86'
  brandStrength: 0.3125
  lightness: 0.51397
  saturation: 0.326013
  rhythmicContrast: 1
purpose:
  - name: null
    item: null
    url: null
