analytics: {}
color:
  brandColors:
    - '#fefefe'
    - '#317ec2'
    - '#001400'
    - '#004252'
    - '#387200'
  brandStrength: 0.15456
  lightness: 0.5076
  rhythmicContrast: 0.233952
  saturation: 0.506756
cta: {}
layout_spectrum: 1
name: chefjohnjoleary
opengraph: {}
purpose:
  - {}
typography_spectrum: 0.25181
