analytics: {}
color:
  brandColors:
    - '#fefefe'
    - '#317ec2'
    - '#001400'
    - '#004252'
    - '#387200'
  brandStrength: 0.19679
  lightness: 0.497466
  rhythmicContrast: 0
  saturation: 0.1875
cta: {}
layout_spectrum: 1
name: chefjohnjoleary
opengraph: {}
purpose:
  - {}
typography_spectrum: 0.25181
