name: chefjohnjoleary
favicon: null
layout_spectrum: 0.24458
typography_spectrum: 0.25181
title: Provincial Serendipity
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fefefe'
    - '#317ec2'
    - '#001400'
    - '#004252'
    - '#387200'
  brandStrength: 0.1875
  lightness: 0.51397
  saturation: 0.326013
  rhythmicContrast: 0.25
purpose:
  - name: null
    item: null
    url: null
