name: chefjohnjoleary
favicon: null
layout_spectrum: 0.25825
typography_spectrum: 0.25181
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fefefe'
    - '#317ec2'
    - '#001400'
    - '#004252'
    - '#387200'
  brandStrength: 0.25
  lightness: 0.3125
  saturation: 0.3125
  rhythmicContrast: 0.25
purpose:
  - name: null
    item: null
    url: null
