analytics: {}
color:
  brandColors:
    - '#fefefe'
    - '#317ec2'
    - '#001400'
    - '#004252'
    - '#387200'
  brandStrength: 0.076858
  lightness: 1
  rhythmicContrast: 0.5
  saturation: 0.1875
cta: {}
layout_spectrum: 0.25825
name: "Chef John J. O'Leary"
opengraph: {}
purpose:
  - {}
typography_spectrum: 0.25181
