name: chefjohnjoleary
favicon: null
layout_spectrum: 0.619087
typography_spectrum: 0.61322
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#C8C0A0'
    - '#787038'
    - '#A89858'
    - '#B86058'
    - '#E8E0C8'
  brandStrength: 0.3125
  lightness: 0.51397
  saturation: 0.326013
  rhythmicContrast: 0.669877
purpose:
  - name: null
    item: null
    url: null
