analytics: {}
color:
  brandColors:
    - '#C8C0A0'
    - '#787038'
    - '#A89858'
    - '#B86058'
    - '#E8E0C8'
  brandStrength: 0.027785
  lightness: 0.513971
  rhythmicContrast: 0.669877
  saturation: 0.212586
cta: {}
layout_spectrum: 0.8396118956374523
name: chefjohnjoleary
opengraph: {}
purpose: {}
typography_spectrum: 0.016615689761279917
